#pragma once

#define HSPI_VERSION_MAJOR 1
#define HSPI_VERSION_MINOR 2
#define HSPI_VERSION_REVISION 0

#define HSPI_VERSION ((HSPI_VERSION_MAJOR << 24) | (HSPI_VERSION_MINOR << 16) | (HSPI_VERSION_REVISION << 8))
